apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx-local:latest
          ports:
            - containerPort: 80
            - containerPort: 443
              protocol: TCP
            - containerPort: 443
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
    - name: https-tcp
      port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
    - name: https-udp
      port: 443
      targetPort: 443
      nodePort: 31443
      protocol: UDP
