apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    # WARN: (Deprecated) kubernetes.io/ingress.class: nginx
    # auto-generate self-signed cert if using ingress-nginx with TLS
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #     - nginx.local
  #   secretName: nginx-tls
  rules:
  - host: nginx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port: 80
